import os
import sys
import pandas as pd
import numpy as np
import joblib

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_DIR = os.path.join(os.path.dirname(BASE_DIR), "models")

# Paths for the Crop Recommendation system
CROP_MODEL_PATH = os.path.join(MODEL_DIR, "crop_recommendation_lgbm.pkl")
CROP_ENCODER_PATH = os.path.join(MODEL_DIR, "crop_label_encoder.pkl")
CROP_SCALER_PATH = os.path.join(MODEL_DIR, "crop_feature_scaler.pkl")

# Path for the Price Forecasts (from the main pipeline)
# Using LightGBM or Moirai CSVs generated by previous scripts
FORECAST_CSV_PATH = os.path.join(os.path.dirname(BASE_DIR), "outputs", "mandi_commodity_all_forecasts_moirai.csv")

def recommend_best_profitable_crop(mandi, n, p, k, temp, humidity, ph, rainfall):
    print("==========================================================")
    print("🌱 INTEGRATED CROP RECOMMENDATION & PRICE FORECASTER")
    print("==========================================================")
    
    # 1. Load Crop Recommendation Models
    if not os.path.exists(CROP_MODEL_PATH):
        print("❌ Error: Crop model not found. Please run 'train_crop_model.py' first.")
        return
        
    crop_model = joblib.load(CROP_MODEL_PATH)
    crop_le = joblib.load(CROP_ENCODER_PATH)
    crop_scaler = joblib.load(CROP_SCALER_PATH)
    
    # Input format: [N, P, K, temp, humidity, ph, rainfall]
    # Note: If Kaggle CSV has Soil Type, this array needs to be modified depending on what `train_crop_model.py` found.
    # Assuming baseline 7 features for this script as it's the standard for Kaggle Crop datasets.
    input_features = np.array([[n, p, k, temp, humidity, ph, rainfall]])
    try:
        input_scaled = crop_scaler.transform(input_features)
    except Exception as e:
        print(f"❌ Feature mismatch. Did your Kaggle dataset have 'Soil Type'? Ensure inputs match train definition: {e}")
        return
    
    # 2. Predict Top Agronomic Crops
    probabilities = crop_model.predict_proba(input_scaled)[0]
    top_3_indices = np.argsort(probabilities)[::-1][:3]
    top_3_crops = crop_le.inverse_transform(top_3_indices)
    top_3_probs = probabilities[top_3_indices]
    
    print(f"\n🌍 Location: {mandi}")
    print(f"🌡️ Weather Conditions -> Temp: {temp}°C | Rainfall: {rainfall}mm | Humidity: {humidity}%")
    print("\n✅ TOP 3 AGRONOMICALLY SUITABLE CROPS:")
    for crop, prob in zip(top_3_crops, top_3_probs):
        print(f"   - {crop.capitalize()} (Feasibility: {prob*100:.2f}%)")
        
    # 3. Integrate with the 14-Day Price Forecast Pipeline
    print("\n💰 EVALUATING MARKET PROFITABILITY (14-Day Forecast)...")
    
    if not os.path.exists(FORECAST_CSV_PATH):
        print(f"\n⚠️ Notice: No existing price forecasts found at {FORECAST_CSV_PATH}.")
        print("💡 To see projected profitability, make sure you ran `forecast_all_moirai.py` or the LightGBM batch forecaster first!")
        print(f"\n🏆 Final Recommendation (Agronomic Only): Grow **{top_3_crops[0].capitalize()}**")
        return
        
    df_forecasts = pd.read_csv(FORECAST_CSV_PATH)
    
    best_crop = top_3_crops[0]
    highest_price = 0
    
    # Capitalize the crops from Kaggle to match the Mandi dataset standard mapping
    for crop in top_3_crops:
        mandi_crop = crop.capitalize()
        subset = df_forecasts[(df_forecasts["Mandi"].str.contains(mandi, case=False, na=False)) & 
                              (df_forecasts["Commodity"].str.contains(mandi_crop, case=False, na=False))]
                              
        if not subset.empty:
            max_price_14_days = subset['pred_modal_price'].max()
            print(f"   📈 {mandi_crop}: Expected Peak Price roughly ₹{max_price_14_days:.2f} / quintal")
            if max_price_14_days > highest_price:
                highest_price = max_price_14_days
                best_crop = mandi_crop
        else:
            print(f"   🤷 {mandi_crop}: No historical/predicted market data for this Mandi.")
            
    print("\n==========================================================")
    if highest_price > 0:
        print(f"🏆 FINAL HYBRID RECOMMENDATION: **{best_crop.upper()}**")
        print(f"   (It has strong agronomic feasibility AND highest expected selling price of ₹{highest_price:.2f}/quintal)")
    else:
        print(f"🏆 FINAL RECOMMENDATION: **{top_3_crops[0].upper()}** (Based entirely on biological conditions)")
    print("==========================================================")


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Hybrid Crop Recommender (Biology + Economics)")
    parser.add_argument("--mandi", required=True, type=str, help="Name of target Mandi/Market (e.g. Pune, Kolar)")
    parser.add_argument("--n", type=float, default=90, help="Nitrogen ratio in soil")
    parser.add_argument("--p", type=float, default=42, help="Phosphorous ratio in soil")
    parser.add_argument("--k", type=float, default=43, help="Potassium ratio in soil")
    parser.add_argument("--ph", type=float, default=6.5, help="Soil pH level")
    
    # We allow the user to manually enter weather OR assume they pull it from the NASA Power API 
    parser.add_argument("--temp", type=float, default=25.0, help="Average Temperature (C)")
    parser.add_argument("--humidity", type=float, default=80.0, help="Relative Humidity (%)")
    parser.add_argument("--rainfall", type=float, default=200.0, help="Rainfall (mm)")
    
    args = parser.parse_args()
    
    recommend_best_profitable_crop(
        mandi=args.mandi,
        n=args.n,
        p=args.p,
        k=args.k,
        temp=args.temp,
        humidity=args.humidity,
        ph=args.ph,
        rainfall=args.rainfall
    )
